[package]
name = "loop_pazzle_web"
version = "0.1.0"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
array-macro = "2.1.5"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }

[lib]
name = "loop_pazzle_web"
path = "src/lib.rs"
crate-type = ["cdylib"]
